 export const Blog={
  "TechnicalRoles": [
    "Software Engineer",
    "DevOps Engineer",
    "System Administrator",
    "Database Administrator",
    "Network Engineer",
    "Security Analyst",
    "Data Scientist",
    "AI/ML Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "Game Developer",
    "Cloud Architect",
    "IT Support Specialist",

    "Project Manager",
    "Product Manager",
    "Business Analyst",
    "UX/UI Designer",
    "Scrum Master",
    "Technical Writer",
    "IT Recruiter",
    "Sales Engineer",
    "Marketing Specialist",
    "SEO Specialist",
    "Customer Success Manager",
    "Account Manager",
    "HR Manager",
    "Training and Development Manager",
    "Compliance Officer"
  ]
}