import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      {/* <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p> */}
      <ul>
        <li>
          <Link to="/landing">Landing</Link>
        </li>
        <li>
          <Link to="/signin">SignIn</Link>
        </li>
        <li>
          <Link to="/frametwo">FrameTwo</Link>
        </li>
        <li>
          <Link to="/signuptwo">SignUpTwo</Link>
        </li>
        <li>
          <Link to="/signupthree">SignUpThree</Link>
        </li>
        <li>
          <Link to="/signupfour">SignUpFour</Link>
        </li>
        <li>
          <Link to="/homepagetwo">HomePageTwo</Link>
        </li>
        <li>
          <Link to="/homepage22">HomePage22</Link>
        </li>
        <li>
          <Link to="/homepage21">HomePage21</Link>
        </li>
        <li>
          <Link to="/homepage21one">HomePage21One</Link>
        </li>
        <li>
          <Link to="/searchbuttonfour">SearchButtonFour</Link>
        </li>
        <li>
          <Link to="/searchbuttontwo">SearchButtonTwo</Link>
        </li>
        <li>
          <Link to="/notificationtwo">NotificationTwo</Link>
        </li>
        <li>
          <Link to="/notification">Notification</Link>
        </li>
        <li>
          <Link to="/notificationone">NotificationOne</Link>
        </li>
        <li>
          <Link to="/messagethree">MessageThree</Link>
        </li>
        <li>
          <Link to="/messagetwo">MessageTwo</Link>
        </li>
        <li>
          <Link to="/message">Message</Link>
        </li>
        <li>
          <Link to="/userprofilefour">UserProfileFour</Link>
        </li>
        <li>
          <Link to="/userprofile">UserProfile</Link>
        </li>
        <li>
          <Link to="/userprofiletwo">UserProfileTwo</Link>
        </li>
        <li>
          <Link to="/userprofilethree">UserProfileThree</Link>
        </li>
        <li>
          <Link to="/userprofileone">UserProfileOne</Link>
        </li>
        <li>
          <Link to="/frame">Frame</Link>
        </li>
        <li>
          <Link to="/signupfive">SignUpFive</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/signupone">SignUpOne</Link>
        </li>
        <li>
          <Link to="/messageone">MessageOne</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
        <li>
          <Link to="/searchbuttonone">SearchButtonOne</Link>
        </li>
        <li>
          <Link to="/searchbuttonthree">SearchButtonThree</Link>
        </li>
        <li>
          <Link to="/homepagethree">HomePageThree</Link>
        </li>
        <li>
          <Link to="/homepagefour">HomePageFour</Link>
        </li>
        <li>
          <Link to="/homepagefive">HomePageFive</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
